trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Free Trial (bd42f546-3318-4407-9700-380997ca0dee)'  # Ensure correct service connection name
    ScriptType: 'InlineScript'
    Inline: |
      Write-Output "Connecting to Azure App Service..."
      $appName = "wordpresstest"
      $resourceGroup = "wordpresstest"
      Restart-AzWebApp -ResourceGroupName $resourceGroup -Name $appName
    azurePowerShellVersion: 'LatestVersion'
- script: |
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    php wp-cli.phar --info
    chmod +x wp-cli.phar
    sudo mv wp-cli.phar /usr/local/bin/wp
    wp cli version
    wp plugin list --path=/home/site/wwwroot --allow-root
  displayName: 'Install WP-CLI'
