trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'MyAzureServiceConnection'  # Ensure correct service connection name
    ScriptType: 'InlineScript'
    Inline: |
      Write-Output "Connecting to Azure App Service..."
      $appName = "wordpresstest"
      $resourceGroup = "wordpresstest"
      Restart-AzWebApp -ResourceGroupName $resourceGroup -Name $appName
    azurePowerShellVersion: 'LatestVersion'

- script: |
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    chmod +x wp-cli.phar
    sudo mv wp-cli.phar /usr/local/bin/wp
    wp --info
    wp cli version
  displayName: 'Install WP-CLI'

- script: |
    mkdir -p ~/wordpress-content
    cd ~/wordpress-content
    echo "Sample WordPress post content" > content.txt
    wp post create ./content.txt --post_title='Sample Post Created with WP-CLI' --post_status=publish --allow-root
  displayName: 'Create WordPress Post'
